[POSUI-224] Support Cash Discount FRD V1.01: Add SELECT_CASH_DISCOUNT and CONFIRM_CASH_PAYMENT broadcasts
PAXTechnologyInc/POSLink-UI pull request #104
Opened 2023-10-24 20:46 UTC by DhruboPaulPax

2024-04-10 18:47 UTC, azvasquez-pax requested changes

2024-04-10 18:47 UTC, azvasquez-pax commented on lib-ui-constant/src/main/java/com/pax/us/pay/ui/constant/entry/OptionEntry.java
> +     * {@link EntryExtraData#PARAM_OPTIONS} : String[] <br>
This is now a Stringified JSON array.
```
Example: "[{title:"Card",amount:1000,currency:"USD"},{title:"Cash",amount:800,currency:"USD"}]"
```

2024-04-23 15:47 UTC, YaninaYang approved these changes
approved on 04/23/2024

2024-04-23 16:01 UTC, azvasquez-pax approved these changes
Approved on 4/23/2024

2024-04-23 16:01 UTC, merged